---

- name: Restart Check_MK
  service:
    name: 'check-mk-raw-{{ checkmk_server__version }}'
    state: restarted

- name: Reload Check_MK configuration
  command: '/omd/sites/{{ checkmk_server__site }}/bin/cmk --reload'
  environment:
    OMD_ROOT: '/omd/sites/{{ checkmk_server__site }}'

- name: Reload apache2
  service:
    name: 'apache2'
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'
