---

- name: Manage Check_MK server
  hosts: [ 'debops_service_checkmk_server' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ checkmk_server__ferm_dependent_rules }}'

    - role: debops-contrib.checkmk_server
      tags: [ 'role::checkmk_server' ]
