---

- name: Manage Check_MK server
  hosts: [ 'debops_service_checkmk_server' ]
  become: True

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ checkmk_server__etc_services__dependent_list }}'
      when: checkmk_server__multisite_livestatus|d()

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ checkmk_server__ferm_dependent_rules }}'

    - role: debops-contrib.checkmk_server
      tags: [ 'role::checkmk_server' ]
